services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EzSystems\EzPlatformAdminUi\Menu\ContentRightSidebarBuilder:
    public: true
    lazy: true
    arguments:
      $userContentTypeIdentifier: '$user_content_type_identifier$'
      $userGroupContentTypeIdentifier: '$user_group_content_type_identifier$'
    tags:
      - { name: knp_menu.menu_builder, method: build, alias: gie_ez_toolblar.menu.content.top_menu }

  EzSystems\EzPlatformAdminUi\Menu\TrashRightSidebarBuilder:
    public: true
    tags:
      - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.trash.sidebar_right }

  EzSystems\EzPlatformAdminUi\Menu\ContentEditRightSidebarBuilder:
    public: true
    tags:
      - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content_edit.sidebar_right }

  EzSystems\EzPlatformAdminUi\Menu\ContentCreateRightSidebarBuilder:
    public: true
    tags:
      - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content_create.sidebar_right }
