services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Gie\EzToolbarBundle\Controller\ToolbarController:
    public: true
    arguments:
      $languages: '$languages$'
      $actionDispatcher: "@ezrepoforms.action_dispatcher.content"

  Gie\EzToolbar\Form\Type\ToolbarType:
    arguments:
      $contentTypeChoiceLoader: '@EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\ContentTypeChoiceLoader'
    tags:
      - { name: form.type }

  Gie\EzToolbar\Form\Event\UrlRedirectProcessor:

  Gie\EzToolbar\Manager\ToolbarManager:

  Gie\EzToolbar\Templating\Twig\ToolbarExtension:
    tags:
      - {name: twig.extension}


  gie_toolbar.admin-ui.controller:
    autowire: true
    autoconfigure: false
    public: false
    class: EzSystems\EzPlatformAdminUiBundle\Controller\ContentViewController
    parent: EzSystems\EzPlatformAdminUiBundle\Controller\Controller

 # gie_toolbar.subscriber:
  #  class: Gie\EzToolbarBundle\EventSubscriber\ToolbarSubscriber
  #  arguments:
  #    $controller: '@gie_toolbar.admin-ui.controller'
  #  tags:
  #    - { name: kernel.event_subscriber }







