services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Gie\EzToolbar\Form\Event\UrlRedirectProcessor:
    decorates: EzSystems\EzPlatformContentForms\Form\Processor\SystemUrlRedirectProcessor
    arguments:
      $siteaccessGroups: '%ezpublish.siteaccess.groups%'
      $systemUrlRedirectProcessor: '@Gie\EzToolbar\Form\Event\UrlRedirectProcessor.inner'


  Gie\EzToolbar\Manager\ToolbarManager:

  Gie\EzToolbar\Templating\Twig\ToolbarExtension:
    tags:
      - {name: twig.extension}


  Gie\EzToolbar\Menu\ContentTopMenuBuilder:
    public: true
    lazy: true
    tags:
      - { name: knp_menu.menu_builder, method: build, alias: gie_ez_toolbar.content.toolbar_menu }









