system:
   rec_edit:
      field_templates:
         - { template: '@ezdesign/content_fields.html.twig', priority: 0 }
         - { template: '@EzPlatformPageFieldType/fields/ezlandingpage.html.twig', priority: 0 }
      fielddefinition_settings_templates:
         - { template: '@EzPlatformPageFieldType/fields/fielddefinition_settings.html.twig' }